# Introduction to Python

## Chapter 2 - Python Lists

### Python Lists

Python Data Types include:
float - real numbers
int - integer numbers
str - string, text
bool - True, False

Each variable represents single value. Data scientists work with many data points. For example, you want to measure the height of everyone in your family, it would be inconvenient to create a new Python variable for each point you collected. 

You can collect the data in a Python list, stored between square brackets [a, b, c]. This data structure can be assigned a variable name by placing the variable name and an equal sign in front of the data structure. A list is a way to give a single name to a collection of values. These values or elements can have any type and can contain different types, even lists. 

In [1]:
[1.73, 1.68, 1.71, 1.89]

[1.73, 1.68, 1.71, 1.89]

In [2]:
fam = [1.73, 1.68, 1.71, 1.89]
fam

[1.73, 1.68, 1.71, 1.89]

In [3]:
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [4]:
fam2 = [['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]
fam2

[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]

In [5]:
type(fam)

list

In [6]:
type(fam2)

list

Like other object types in Python, lists have specific functionality and behavior associated with the object type.

### Exercise 1

#### Create a list
As opposed to int, bool etc., a list is a compound data type; you can group values together: <br>
a = "is"<br>
b = "nice"<br>
my_list = ["my", "list", a, b]<br>
After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables for now, as shown in the script.

__Instructions:__
* Create a list, areas, that contains the area of the hallway (hall), kitchen (kit), living room (liv), bedroom (bed) and bathroom (bath), in this order. Use the predefined variables.
* Print areas with the print() function.

In [7]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv,bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


The printout of the previous exercise wasn't really satisfying. It's just a list of numbers representing the areas, but you can't tell which area corresponds to which part of your house. Build the list so that the list first contains the name of each room as a string and then its area.

#### Create list with different types
A list can contain any Python type. Although it's not really common, a list can also contain a mix of Python types including strings, floats, booleans, etc. The printout of the previous exercise wasn't really satisfying. It's just a list of numbers representing the areas, but you can't tell which area corresponds to which part of your house.The code below is the start of a solution. For some of the areas, the name of the corresponding room is already placed in front. Pay attention here! "bathroom" is a string, while bath is a variable that represents the float 9.50 you specified earlier.

__Instructions:__
* Finish the line of code that creates the areas list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings "hallway", "kitchen" and "bedroom" at the appropriate locations.
* Print areas again; is the printout more informative this time?

In [8]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


#### List of lists
As a data scientist, you'll often be dealing with a lot of data, and it will make sense to group some of this data. Instead of creating a flat list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists. The script below can already give you an idea. <br>
<br>
Don't get confused here: "hallway" is a string, while hall is a variable that represents the float 11.25 you specified earlier.

__Instructions:__
* Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
* Print out house; does this way of structuring your data make more sense?
* Print out the type of house. Are you still dealing with a list?

In [9]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


### Subsetting Lists

To access individual elements from a list, Python uses zero indexing. If you look at the fam list:

In [10]:
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

The first element in the list has index 0, the second element has index 1 and so on. Supposed you want to select the height of Emma, the 4th element, therefore index 3, you put the index inside square brackets after the name of the list:

In [11]:
fam[3]

1.68

In [12]:
fam[6]

'dad'

With zero index, you can count backwards using negative index, but starting with negative 1. Useful when you want to get elements at the end of your list. To get Dad's height, use the index -1:

In [13]:
fam[-1]

1.89

#### List Slicing

To select multiple elements from a list, you use list slicing and thus create a new list. You do this by specifying a range, using a colon : to separate the first element you want to start with a the last element+1 that you want to end with. The first element is included and the last element is excluded. 
listname[start   :   end   ]
        inclusive   exclusive

In [14]:
fam[3:5]

[1.68, 'mom']

You can also leave out the index before or after the colon. If you leave out the index where the slice should begin, you're telling Python to start the slice from index 0. If you leave out the index after the colon, you are telling Python to include all elements, up to and including the last element.

In [15]:
fam[:4]

['liz', 1.73, 'emma', 1.68]

In [16]:
fam[5:]

[1.71, 'dad', 1.89]

### Exercise 2

#### Subset and conquer
Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1. You can also use negative indexing.<br>
x = ["a", "b", "c", "d"]<br>
x[1]<br>
x[-3] # same result!<br>

Remember the areas list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?

__Instructions:__
* Print out the second element from the areas list (it has the value 11.25).
* Subset and print out the last element of areas, being 9.50. Using a negative index makes sense here!
* Select the number representing the area of the living room (20.0) and print it out.

In [18]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


#### Subset and calculate

After you've extracted values from a list, you can use them to perform additional calculations. Take this example, where the second and fourth element of a list x are extracted. The strings that result are pasted together using the + operator:<br>
x = ["a", "b", "c", "d"] <br>
print(x[1] + x[3])<br>

__Instructions:__
* Using a combination of list subsetting and variable assignment, create a new variable, eat_sleep_area, that contains the sum of the area of the kitchen and the area of the bedroom.
* Print the new variable eat_sleep_area

In [17]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


#### Slicing and dicing
Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:<br>
my_list[start:end]<br>
The start index will be included, while the end index is not.<br>
The code sample below shows an example. A list with "b" and "c", corresponding to indexes 1 and 2, are selected from a list x:<br>
x = ["a", "b", "c", "d"]<br>
x[1:3]<br>
The elements with index 1 and 2 are included, while the element with index 3 is not.

__Instructions:__
* Use slicing to create a list, downstairs, that contains the first 6 elements of areas.
* Do a similar thing to create a new variable, upstairs, that contains the last 4 elements of areas.
* Print both downstairs and upstairs using print()

In [19]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


#### Slicing and dicing (2)
In the video, Hugo first discussed the syntax where you specify both where to begin and end the slice of your list:
my_list[begin:end]. However, it's also possible not to specify these indexes. If you don't specify the begin index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the end index, the slice will go all the way to the last element of your list. To experiment with this, try the following commands in the IPython Shell:<br>
x = ["a", "b", "c", "d"]<br>
x[:2]<br>
x[2:]<br>
x[:]

__Instructions:__
* Create downstairs again, as the first 6 elements of areas. This time, simplify the slicing by omitting the begin index.
* Create upstairs again, as the last 4 elements of areas. This time, simplify the slicing by omitting the end index.

In [20]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[6:]

### Manipulating Lists

#### Changing List Elements

To change list elements, you use the subset to select an element and then assign a new value using the equal sign. Let's say Emma has grown since the fam list was made, to change her height you select her height index and assign a new value.

In [21]:
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam[3] = 1.70
fam

['liz', 1.73, 'emma', 1.7, 'mom', 1.71, 'dad', 1.89]

You can even change whole list slice at once by select the slice you want to modify and assign a new list to it

In [31]:
fam[0:2] = ['lisa', 1.74]


['lisa', 1.74, 'emma', 1.7, 'mom', 1.71, 'dad', 1.89]

#### Adding and Removing Elements
The plus operator (+) works differently for lists. If you use the plus operator between two lists, Python pastes the contents together and makes a new list.

In [22]:
fam + ['me', 1.60]

['liz', 1.73, 'emma', 1.7, 'mom', 1.71, 'dad', 1.89, 'me', 1.6]

Deleting elements is similar in that you select the element or slice you want to delete and apply del() to that selection. If you remove index 2 from the fam list, you remove Emma and all elements move up in their index position. If you run the same delete selection again, you remove Emma's height as well. 

In [23]:
del(fam[2])
fam

['liz', 1.73, 1.7, 'mom', 1.71, 'dad', 1.89]

In [24]:
del(fam[2])
fam

['liz', 1.73, 'mom', 1.71, 'dad', 1.89]

#### Behind the Scenes Important Things to Know
When you create a list X (x = [a, b, c, d], list X has references to each item in the list and the items themselves are stored individually in memory. That means if you create a new list Y (y = x) and change index 1 in y (y[1] = z) and then print out list X, x will now read: [a, z, c, d]. To create a new list Y that stores its elements in a new location in memory, you can:
y = list(x)
Or
y = x[:]

### Exercise 3

#### Replace list elements
Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once. Use the IPython Shell to experiment with the commands below. Can you tell what's happening and why?<br>
x = ["a", "b", "c", "d"]<br>
x[1] = "r"<br>
x[2:] = ["s", "t"]<br>
For this and the following exercises, you'll continue working on the areas list that contains the names and areas of different rooms in a house.

__Instructions:__
* Update the area of the bathroom area to be 10.50 square meters instead of 9.50.
* Make the areas list more trendy! Change "living room" to "chill zone".

In [25]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

#### Extend a list
If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the + operator:<br>
x = ["a", "b", "c", "d"]<br>
y = x + ["e", "f"]<br>
You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the areas list?

__Instructions:__
* Use the + operator to paste the list ["poolhouse", 24.5] to the end of the areas list. Store the resulting list as areas_1.
* Further extend areas_1 by adding data on your garage. Add the string "garage" and float 15.45. Name the resulting list areas_2

In [26]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

#### Delete list elements
Finally, you can also remove elements from your list. You can do this with the del statement:<br>
x = ["a", "b", "c", "d"]<br>
del(x[1])<br>
Pay attention here: as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!<br>
The updated and extended version of areas that you've built in the previous exercises is coded below. You can copy and paste this into the IPython Shell to play around with the result.<br>
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]<br>
There was a mistake! The amount you won with the lottery is not that big after all and it looks like the poolhouse isn't going to happen. You decide to remove the corresponding string and float from the areas list.
The ; sign is used to place commands on the same line. The following two code chunks are equivalent:<br>
__Same line__<br>
command1; command2
<br>
__Separate lines__<br>
command1<br>
command2

In [28]:
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0, "bedroom", 10.75, "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

#Delete the corresponding string and float for the poolhouse using the semi-colon
del(areas[-3]) ; del(areas[-3])
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5,
 'garage',
 15.45]

#### Inner workings of lists
At the end of the video, Hugo explained how Python lists work behind the scenes. In this exercise you'll get some hands-on experience with this. The Python code in the script already creates a list with the name areas and a copy named areas_copy. Next, the first element in the areas_copy list is changed and the areas list is printed out. If you hit Run Code you'll see that, although you've changed areas_copy, the change also takes effect in the areas list. That's because areas and areas_copy point to the same list. <br>
If you want to prevent changes in areas_copy from also taking effect in areas, you'll have to do a more explicit copy of the areas list. You can do this with list() or by using [:].

__Instructions:__
* Change the second command, that creates the variable areas_copy, such that areas_copy is an explicit copy of areas. After your edit, changes made to areas_copy shouldn't affect areas. Hit Submit Answer to check this.

In [29]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)
areas_copy = areas[:]

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


See how even though you changed areas_copy, it also changes areas because the two variable names are reading the same memory address. 

In [30]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

#Create areas_copy by creating a new list that has the same elements as area
areas_copy = list(areas)

#Change areas_copy
areas_copy[0] = 5

#Print both
print(areas)
print(areas_copy)

[11.25, 18.0, 20.0, 10.75, 9.5]
[5, 18.0, 20.0, 10.75, 9.5]
